version: "3.9"
services:

  madelife:
    build: .
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - .:/var/www/html
    links: 
    - db
  db:
    image: mysql:5.7
    volumes:
    - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: madelife
      MYSQL_USER: madelife
      MYSQL_PASSWORD: 123456
  phpmyadmin:
    links:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456
      UPLOAD_LIMIT: 500M