<?php

namespace App\Http\Controllers\Web\Protocolos;

use App\Http\Controllers\Controller;
use App\Models\Anexo;
use App\Models\ProtocoloAvaliacaoFerida;
use App\Models\ProtocoloAvaliacaoLaserTerapia;
use App\Models\ProtocoloAvaliacaoLesaoPressao;
use App\Models\ProtocoloAvaliacaoPesDiabetico;
use App\Models\ProtocoloCausaFerida;
use App\Models\ProtocoloDiagnosticoFerida;
use App\Models\ProtocoloSinaisSintomaFeridas;
use App\Models\ProtocoloSkin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ProtocoloAvaliacaoFeridaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $empresa_id = $request->user()->pessoa->profissional->empresa_id;
        return ProtocoloAvaliacaoFerida::with('protocolo' ,'protocolo.cliente.pessoa', 'protocolo.paciente.pessoa' ,'protocololesao', 'protocolopesdiabeticos', 'protocololaserterapia', 'protocololaserterapia.protocolodiagnostico', 'protocololaserterapia.protocolodiagnostico.protocolocausa', 'protocololaserterapia.protocolodiagnostico.protocolosintomas')
        ->where('empresa_id', $empresa_id)
        ->get();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $empresa_id = Auth::user()->pessoa->profissional->empresa_id;

        DB::transaction(function () use ($request, $empresa_id){
            $protocoloAvaliacaoFerida = ProtocoloAvaliacaoFerida::create([
                'empresa_id'                => $request['empresa_id'],
                'protocolo_id' => ProtocoloSkin::firstOrCreate([
                    'empresa_id'             => $request['empresa_id'],
                    'paciente_id'            => $request['protocolo']['paciente_id'],
                    'cliente_id'             => $request['protocolo']['cliente_id'],
                    'medico'                 => $request['protocolo']['medico'],
                    'diagnostico'            => $request['protocolo']['diagnostico'],
                    'afastado'               => $request['protocolo']['afastado'],
                    'aposentado'             => $request['protocolo']['aposentado'],
                    'nivel_consciencia'      => $request['protocolo']['nivel_consciencia'],
                    'obs_nivel_consciencia'  => $request['protocolo']['obs_nivel_consciencia'],
                    'hipertensao_arterial'   => $request['protocolo']['hipertensao_arterial'],
                    'pa'                     => $request['protocolo']['pa'],
                    'data'                     => $request['protocolo']['data'],
                    'diabetes'               => $request['protocolo']['diabetes'],
                    'glicemia'               => $request['protocolo']['glicemia'],
                    'hematocrito'            => $request['protocolo']['hematocrito'],
                    'hemoglobina'            => $request['protocolo']['hemoglobina'],
                    'proteinas_totais'       => $request['protocolo']['proteinas_totais'],
                    'pcr'                    => $request['protocolo']['pcr'],
                    'albumina'               => $request['protocolo']['albumina'],
                    'outros'                 => $request['protocolo']['outros'],
                    'peso'                   => $request['protocolo']['peso'],
                    'altura'                 => $request['protocolo']['altura'],
                    'acamado'                => $request['protocolo']['acamado'],
                    'deambula'               => $request['protocolo']['deambula'],
                    'cadeira_rodas'          => $request['protocolo']['cadeira_rodas'],
                    'muleta'                 => $request['protocolo']['muleta'],
                    'andador'                => $request['protocolo']['andador'],
                    'c_ajuda'                => $request['protocolo']['c_ajuda'],
                    'destreza_manual'        => $request['protocolo']['destreza_manual'],
                    'auto_cuidado'           => $request['protocolo']['auto_cuidado'],
                    'cafe_manha'             => $request['protocolo']['cafe_manha'],
                    'almoco'                 => $request['protocolo']['almoco'],
                    'cafe_tarde'             => $request['protocolo']['cafe_tarde'],
                    'jantar'                 => $request['protocolo']['jantar'],
                    'ceia'                   => $request['protocolo']['ceia'],
                    'rica'                   => $request['protocolo']['rica'],
                    'urinaria'               => $request['protocolo']['urinaria'],
                    'fecal'                  => $request['protocolo']['fecal'],
                    'medicamento'            => $request['protocolo']['medicamento'],
                    'av_central'             => $request['protocolo']['av_central'],
                    'av_periferico'          => $request['protocolo']['av_periferico'],
                    'av_jelco'               => $request['protocolo']['av_jelco'],
                    'av_scalp'               => $request['protocolo']['av_scalp'],
                    'av_intracath'           => $request['protocolo']['av_intracath'],
                    'av_portocath'           => $request['protocolo']['av_portocath'],
                    'av_piv'                 => $request['protocolo']['av_piv'],
                    'av_data'                => $request['protocolo']['av_data'],
                    'tbg_fuma'               => $request['protocolo']['tbg_fuma'],
                    'tbg_tempo'              => $request['protocolo']['tbg_tempo'],
                    'tbg_cigarros_dia'       => $request['protocolo']['tbg_cigarros_dia'],
                    'tbg_atual'              => $request['protocolo']['tbg_atual'],
                    'tbg_tempo_parou'        => $request['protocolo']['tbg_tempo_parou'],
                    'alergia'                => $request['protocolo']['alergia'],
                    'alergia_qual'           => $request['protocolo']['alergia_qual'],
                    'oxigenioterapia'        => $request['protocolo']['oxigenioterapia'],
                    'ox_cateter_nasal'       => $request['protocolo']['ox_cateter_nasal'],
                    'ox_mascara_nebulizacao' => $request['protocolo']['ox_mascara_nebulizacao'],
                    'ox_cateter_venturi'     => $request['protocolo']['ox_cateter_venturi'],
                    'ox_bipap'               => $request['protocolo']['ox_bipap'],
                    'ox_cpap'                => $request['protocolo']['ox_cpap'],
                    'al_vo'                  => $request['protocolo']['al_vo'],
                    'al_sng'                 => $request['protocolo']['al_sng'],
                    'al_sne'                 => $request['protocolo']['al_sne'],
                    'al_gastrostomia'        => $request['protocolo']['al_gastrostomia'],
                    'al_jejunostomia'        => $request['protocolo']['al_jejunostomia'],
                    'al_parenteral'          => $request['protocolo']['al_parenteral'],
                    'as_sozinho'             => $request['protocolo']['as_sozinho'],
                    'as_familiares'          => $request['protocolo']['as_familiares'],
                    'as_cuidador'            => $request['protocolo']['as_cuidador'],
                    'as_casa_terrea'         => $request['protocolo']['as_casa_terrea'],
                    'as_apartamento'         => $request['protocolo']['as_apartamento'],
                    'as_casa_escadas'        => $request['protocolo']['as_casa_escadas'],
                    'as_outros'              => $request['protocolo']['as_outros'],
                    'cp_normal'              => $request['protocolo']['cp_normal'],
                    'cp_seca'                => $request['protocolo']['cp_seca'],
                    'cp_oleosa'              => $request['protocolo']['cp_oleosa'],
                    'cp_mista'               => $request['protocolo']['cp_mista'],
                    'cp_ressecada'           => $request['protocolo']['cp_ressecada'],
                    'cp_outra'               => $request['protocolo']['cp_outra'],
                    'ds_visao'               => $request['protocolo']['ds_visao'],
                    'ds_audicao'             => $request['protocolo']['ds_audicao'],
                    'cpa_pele_oleosa'        => $request['protocolo']['cpa_pele_oleosa'],
                    'cpa_cicatriz'           => $request['protocolo']['cpa_cicatriz'],
                    'cpa_dobras_gordura'     => $request['protocolo']['cpa_dobras_gordura'],
                    'cpa_dermatologica'      => $request['protocolo']['cpa_dermatologica'],
                    'cpa_atual'              => $request['protocolo']['cpa_atual'],
                    'cpa_qual'               => $request['protocolo']['cpa_qual'],
                    'crd_lesoes'             => $request['protocolo']['crd_lesoes'],
                    'crd_fistulas'           => $request['protocolo']['crd_fistulas'],
                    'crd_fisuras'            => $request['protocolo']['crd_fisuras'],
                    'crd_incontinencia'      => $request['protocolo']['crd_incontinencia'],
                    'crd_outros'             => $request['protocolo']['crd_outros'],
                ])->id,
                    'ferida_cirurgica'              => $request['ferida_cirurgica'],
                    'ferida_lesao_pressao'          => $request['ferida_lesao_pressao'],
                    'ferida_diabetica'              => $request['ferida_diabetica'],
                    'ferida_venosa'                 => $request['ferida_venosa'],
                    'ferida_arterial'               => $request['ferida_arterial'],
                    'ferida_outros'                 => $request['ferida_outros'],
                    'tempo_lesao'                   => $request['tempo_lesao'],
                    'feridas_anteriores'            => $request['feridas_anteriores'],
                    'popliteo_d'                    => $request['popliteo_d'],
                    'popliteo_e'                    => $request['popliteo_e'],
                    'pedial_d'                      => $request['pedial_d'],
                    'pedial_e'                      => $request['pedial_e'],
                    'perfusao_menor'                => $request['perfusao_menor'],
                    'perfusao_maior'                => $request['perfusao_maior'],
                    'mensuracao_anterior'           => $request['mensuracao_anterior'],
                    'mensuracao_atual'              => $request['mensuracao_atual'],
                    'lp_1'                          => $request['lp_1'],
                    'lp_2'                          => $request['lp_2'],
                    'lp_3'                          => $request['lp_3'],
                    'lp_4'                          => $request['lp_4'],
                    'lp_dispositivo_medico'         => $request['lp_dispositivo_medico'],
                    'lp_ltp'                        => $request['lp_ltp'],
                    'lp_impossivel_estadiar'        => $request['lp_impossivel_estadiar'],
                    'skin_1'                        => $request['skin_1'],
                    'skin_2'                        => $request['skin_2'],
                    'skin_3'                        => $request['skin_3'],
                    'venosa_superficial'            => $request['venosa_superficial'],
                    'venosa_parcial'                => $request['venosa_parcial'],
                    'venosa_total'                  => $request['venosa_total'],
                    'leitof_granulacao'             => $request['leitof_granulacao'],
                    'leitof_esfacelo'               => $request['leitof_esfacelo'],
                    'leitof_necrose'                => $request['leitof_necrose'],
                    'leitof_biofilme'               => $request['leitof_biofilme'],
                    'leitof_outros'                 => $request['leitof_outros'],
                    'leitof_gangrena'               => $request['leitof_gangrena'],
                    'desbridamento_autolitico'      => $request['desbridamento_autolitico'],
                    'desbridamento_enzimatico'      => $request['desbridamento_enzimatico'],
                    'desbridamento_mecanico'        => $request['desbridamento_mecanico'],
                    'desbridamento_cirurgico'       => $request['desbridamento_cirurgico'],
                    'margem_epitelizada'            => $request['margem_epitelizada'],
                    'margem_epitelizando'           => $request['margem_epitelizando'],
                    'margem_necrosada'              => $request['margem_necrosada'],
                    'margem_hiperemiada'            => $request['margem_hiperemiada'],
                    'margem_epibole'                => $request['margem_epibole'],
                    'margem_aderida'                => $request['margem_aderida'],
                    'margem_descolada_total'        => $request['margem_descolada_total'],
                    'margem_descolada_parcial'      => $request['margem_descolada_parcial'],
                    'descolada_parcial_hrs'         => $request['descolada_parcial_hrs'],
                    'descolada_parcial_cm'          => $request['descolada_parcial_cm'],
                    'margem_outros'                 => $request['margem_outros'],
                    'pele_hiperemiada'              => $request['pele_hiperemiada'],
                    'pele_ressecada'                => $request['pele_ressecada'],
                    'pele_queratose'                => $request['pele_queratose'],
                    'pele_eczema'                   => $request['pele_eczema'],
                    'pele_lesoes'                   => $request['pele_lesoes'],
                    'pele_dermatite'                => $request['pele_dermatite'],
                    'pele_outro'                    => $request['pele_outro'],
                    'exsudato_seroso'               => $request['exsudato_seroso'],
                    'exsudato_translucido'          => $request['exsudato_translucido'],
                    'exsudato_sanguinolento'        => $request['exsudato_sanguinolento'],
                    'exsudato_serosanguinolento'    => $request['exsudato_serosanguinolento'],
                    'exsudato_purulento'            => $request['exsudato_purulento'],
                    'exsudato_piosanguinolento'     => $request['exsudato_piosanguinolento'],
                    'exsudato_esverdeado'           => $request['exsudato_esverdeado'],
                    'exsudato_outro'                => $request['exsudato_outro'],
                    'volume_escasso'                => $request['volume_escasso'],
                    'volume_pequeno'                => $request['volume_pequeno'],
                    'volume_moderado'               => $request['volume_moderado'],
                    'volume_grande'                 => $request['volume_grande'],
                    'volume_abundante'              => $request['volume_abundante'],
                    'coleta_cultura'                => $request['coleta_cultura'],
                    'coleta_cultura_resultado'      => $request['coleta_cultura_resultado'],

                    'protocololesao_id' => ProtocoloAvaliacaoLesaoPressao::create([
                        'braden_total_limitado'            => $request['lesao_pressao']['braden_total_limitado'],
                        'braden_muito_limitado'            => $request['lesao_pressao']['braden_muito_limitado'],
                        'braden_levemente_limitado'        => $request['lesao_pressao']['braden_levemente_limitado'],
                        'braden_nenhuma_limitacao'         => $request['lesao_pressao']['braden_nenhuma_limitacao'],
                        'braden_completamente_molhada'     => $request['lesao_pressao']['braden_completamente_molhada'],
                        'braden_muito_molhada'             => $request['lesao_pressao']['braden_muito_molhada'],
                        'braden_ocasionalmente_molhada'    => $request['lesao_pressao']['braden_ocasionalmente_molhada'],
                        'braden_raramente_molhada'         => $request['lesao_pressao']['braden_raramente_molhada'],
                        'braden_acamado'                   => $request['lesao_pressao']['braden_acamado'],
                        'braden_confinado_cadeira'         => $request['lesao_pressao']['braden_confinado_cadeira'],
                        'braden_anda_ocasionalmente'       => $request['lesao_pressao']['braden_anda_ocasionalmente'],
                        'braden_anda_frequentemente'       => $request['lesao_pressao']['braden_anda_frequentemente'],
                        'braden_totalmente_imovel'         => $request['lesao_pressao']['braden_totalmente_imovel'],
                        'braden_bastante_limitado'         => $request['lesao_pressao']['braden_bastante_limitado'],
                        'braden_levemente_limitado2'       => $request['lesao_pressao']['braden_levemente_limitado2'],
                        'braden_nenhuma_limitacao2'        => $request['lesao_pressao']['braden_nenhuma_limitacao2'],
                        'braden_muito_pobre'               => $request['lesao_pressao']['braden_muito_pobre'],
                        'braden_provavelmente_inadequado'  => $request['lesao_pressao']['braden_provavelmente_inadequado'],
                        'braden_adequado'                  => $request['lesao_pressao']['braden_adequado'],
                        'braden_excelente'                 => $request['lesao_pressao']['braden_excelente'],
                        'braden_problema'                  => $request['lesao_pressao']['braden_problema'],
                        'braden_problema_potencial'        => $request['lesao_pressao']['braden_problema_potencial'],
                        'braden_nenhum_problema'           => $request['lesao_pressao']['braden_nenhum_problema'],
                        'colchao_inadequado'               => $request['lesao_pressao']['colchao_inadequado'],
                        'colchao_agua'                     => $request['lesao_pressao']['colchao_agua'],
                        'colchao_ar'                       => $request['lesao_pressao']['colchao_ar'],
                        'colchao_piramidal'                => $request['lesao_pressao']['colchao_piramidal'],
                        'protetor'                         => $request['lesao_pressao']['protetor'],
                        'protetor_espuma'                  => $request['lesao_pressao']['protetor_espuma'],
                        'protetor_agua'                    => $request['lesao_pressao']['protetor_agua'],
                        'protetor_ar'                      => $request['lesao_pressao']['protetor_ar'],
                        'protetor_gel'                     => $request['lesao_pressao']['protetor_gel'],
                        'posicionadores'                   => $request['lesao_pressao']['posicionadores'],
                        'posicionadores_regiao'            => $request['lesao_pressao']['posicionadores_regiao'],
                        'banho_leito'                      => $request['lesao_pressao']['banho_leito'],
                        'banho_aspersao'                   => $request['lesao_pressao']['banho_aspersao'],
                        'banho_frequencia'                 => $request['lesao_pressao']['banho_frequencia'],
                        'higiene_intima'                   => $request['lesao_pressao']['higiene_intima'],
                        'sabonetes'                        => $request['lesao_pressao']['sabonetes'],
                        'hidratantes'                      => $request['lesao_pressao']['hidratantes'],
                        'hidratantes_qual'                 => $request['lesao_pressao']['hidratantes_qual'],
                        'cuidador_nome'                    => $request['lesao_pressao']['cuidador_nome'],
                        // 'cuidador_idade'                   => $request['lesao_pressao']['cuidador_idade'],
                        'cuidador_data_nasc'               => $request['lesao_pressao']['cuidador_data_nasc'],
                        'cuidador_disponibilidade'         => $request['lesao_pressao']['cuidador_disponibilidade'],
                        'cuidador_observacoes'             => $request['lesao_pressao']['cuidador_observacoes'],
                    ])->id,

                    'protocolopesdiabeticos_id' => ProtocoloAvaliacaoPesDiabetico::create([
                        'pe_esquerdo_calos1'      => $request['pe_diabetico']['pe_esquerdo_calos1'],
                        'pe_esquerdo_calos2'      => $request['pe_diabetico']['pe_esquerdo_calos2'],
                        'pe_esquerdo_calos3'      => $request['pe_diabetico']['pe_esquerdo_calos3'],
                        'pe_esquerdo_calos4'      => $request['pe_diabetico']['pe_esquerdo_calos4'],
                        'pe_esquerdo_ulcera1'     => $request['pe_diabetico']['pe_esquerdo_ulcera1'],
                        'pe_esquerdo_ulcera2'     => $request['pe_diabetico']['pe_esquerdo_ulcera2'],
                        'pe_esquerdo_ulcera3'     => $request['pe_diabetico']['pe_esquerdo_ulcera3'],
                        'pe_esquerdo_ulcera4'     => $request['pe_diabetico']['pe_esquerdo_ulcera4'],
                        'pe_esquerdo_preulcera1'  => $request['pe_diabetico']['pe_esquerdo_preulcera1'],
                        'pe_esquerdo_preulcera2'  => $request['pe_diabetico']['pe_esquerdo_preulcera2'],
                        'pe_esquerdo_preulcera3'  => $request['pe_diabetico']['pe_esquerdo_preulcera3'],
                        'pe_esquerdo_preulcera4'  => $request['pe_diabetico']['pe_esquerdo_preulcera4'],
                        'pe_direito_calos1'       => $request['pe_diabetico']['pe_direito_calos1'],
                        'pe_direito_calos2'       => $request['pe_diabetico']['pe_direito_calos2'],
                        'pe_direito_calos3'       => $request['pe_diabetico']['pe_direito_calos3'],
                        'pe_direito_calos4'       => $request['pe_diabetico']['pe_direito_calos4'],
                        'pe_direito_ulcera1'      => $request['pe_diabetico']['pe_direito_ulcera1'],
                        'pe_direito_ulcera2'      => $request['pe_diabetico']['pe_direito_ulcera2'],
                        'pe_direito_ulcera3'      => $request['pe_diabetico']['pe_direito_ulcera3'],
                        'pe_direito_ulcera4'      => $request['pe_diabetico']['pe_direito_ulcera4'],
                        'pe_direito_preulcera1'   => $request['pe_diabetico']['pe_direito_preulcera1'],
                        'pe_direito_preulcera2'   => $request['pe_diabetico']['pe_direito_preulcera2'],
                        'pe_direito_preulcera3'   => $request['pe_diabetico']['pe_direito_preulcera3'],
                        'pe_direito_preulcera4'   => $request['pe_diabetico']['pe_direito_preulcera4'],
                        'monofilamento'           => $request['pe_diabetico']['monofilamento'],
                    ])->id,

                    'protocololaserterapia_id' => ProtocoloAvaliacaoLaserTerapia::create([
                        'laserterapia_localizacao'          => $request['laserterapia']['laserterapia_localizacao'],
                        'tratamento_ferida_cirurgica'       => $request['laserterapia']['tratamento_ferida_cirurgica'],
                        'tratamento_ferida_lesao_pressao'   => $request['laserterapia']['tratamento_ferida_lesao_pressao'],
                        'tratamento_ferida_neuropatica'     => $request['laserterapia']['tratamento_ferida_neuropatica'],
                        'tratamento_ferida_venosa'          => $request['laserterapia']['tratamento_ferida_venosa'],
                        'tratamento_ferida_arterial'        => $request['laserterapia']['tratamento_ferida_arterial'],
                        'tratamento_ferida_outros'          => $request['laserterapia']['tratamento_ferida_outros'],
                        'estadiamento'                      => $request['laserterapia']['estadiamento'],
                        'mensuracao'                        => $request['laserterapia']['mensuracao'],
                        'leito_ferida'                      => $request['laserterapia']['leito_ferida'],
                        'margem_ferida'                     => $request['laserterapia']['margem_ferida'],
                        'pele_redor'                        => $request['laserterapia']['pele_redor'],
                        'exsudato'                          => $request['laserterapia']['exsudato'],
                        'classificacao_dor'                 => $request['laserterapia']['classificacao_dor'],
                        'area_lesao_larg'                   => $request['laserterapia']['area_lesao_larg'],
                        'area_lesao_comp'                   => $request['laserterapia']['area_lesao_comp'],
                        'energia_total_j'                   => $request['laserterapia']['energia_total_j'],
                        'energia_total_area'                => $request['laserterapia']['energia_total_area'],
                        'pontos_area_afetada'               => $request['laserterapia']['pontos_area_afetada'],
                        'area_afetada_pontos'               => $request['laserterapia']['area_afetada_pontos'],
                        'area_afetada_v'                    => $request['laserterapia']['area_afetada_v'],
                        'area_afetada_if'                   => $request['laserterapia']['area_afetada_if'],
                        'area_afetada_pontual'              => $request['laserterapia']['area_afetada_pontual'],
                        'area_afetada_varredura'            => $request['laserterapia']['area_afetada_varredura'],
                        'pontos_redor_area'                 => $request['laserterapia']['pontos_redor_area'],
                        'redor_area_pontos'                 => $request['laserterapia']['redor_area_pontos'],
                        'redor_area_v'                      => $request['laserterapia']['redor_area_v'],
                        'redor_area_if'                     => $request['laserterapia']['redor_area_if'],
                        'escala_dor_obs'                    => $request['laserterapia']['escala_dor_obs'],

                        'pro_diagnostico_id' => ProtocoloDiagnosticoFerida::create([
                            'integridade_tissular'  => $request['diagnostico']['integridade_tissular'],
                            'risco_infeccao'        => $request['diagnostico']['risco_infeccao'],
                            'alt_temperatura'       => $request['diagnostico']['alt_temperatura'],
                            'diagnostico_vazio'     => $request['diagnostico']['diagnostico_vazio'],
                            'dor_aguda'             => $request['diagnostico']['dor_aguda'],
                            'dor_cronica'           => $request['diagnostico']['dor_cronica'],
                            'mobilidade_fisica'     => $request['diagnostico']['mobilidade_fisica'],
                            'alt_eliminacoes'       => $request['diagnostico']['alt_eliminacoes'],
                            'risco_glicemia'        => $request['diagnostico']['risco_glicemia'],

                            'protocolocausa_id' => ProtocoloCausaFerida::create([
                                'circulacao_prejudicada'           => $request['diagnostico']['causa']['circulacao_prejudicada'],
                                'conhecimento_insuf'               => $request['diagnostico']['causa']['conhecimento_insuf'],
                                'integridade_inflamacao'           => $request['diagnostico']['causa']['integridade_inflamacao'],
                                'lesao_tecido_subcutaneo'          => $request['diagnostico']['causa']['lesao_tecido_subcutaneo'],
                                'lesao_tecido_epidermico'          => $request['diagnostico']['causa']['lesao_tecido_epidermico'],
                                'tumores'                          => $request['diagnostico']['causa']['tumores'],
                                'fratura'                          => $request['diagnostico']['causa']['fratura'],
                                'integridade_trauma'               => $request['diagnostico']['causa']['integridade_trauma'],
                                'edema'                            => $request['diagnostico']['causa']['edema'],
                                'exp_umidade_excessiva'            => $request['diagnostico']['causa']['exp_umidade_excessiva'],
                                'mudancas_turgor_pele'             => $request['diagnostico']['causa']['mudancas_turgor_pele'],
                                'proeminencias_osseas'             => $request['diagnostico']['causa']['proeminencias_osseas'],
                                'ulceras_pressao'                  => $request['diagnostico']['causa']['ulceras_pressao'],
                                'fragilidade_pele'                 => $request['diagnostico']['causa']['fragilidade_pele'],
                                'imobilidade'                      => $request['diagnostico']['causa']['imobilidade'],
                                'ferida_cirurgica'                 => $request['diagnostico']['causa']['ferida_cirurgica'],
                                'ulceras_etiologias'               => $request['diagnostico']['causa']['ulceras_etiologias'],
                                'doencas_pele'                     => $request['diagnostico']['causa']['doencas_pele'],
                                'integridade_outro'                => $request['diagnostico']['causa']['integridade_outro'],
                                'agente_farmaceutico'              => $request['diagnostico']['causa']['agente_farmaceutico'],
                                'conhecimento_insu_expo_patogenos' => $request['diagnostico']['causa']['conhecimento_insu_expo_patogenos'],
                                'defesas_primarias'                => $request['diagnostico']['causa']['defesas_primarias'],
                                'defesas_secundarias'              => $request['diagnostico']['causa']['defesas_secundarias'],
                                'infeccao_desnutricao'             => $request['diagnostico']['causa']['infeccao_desnutricao'],
                                'destruicao_tecidos'               => $request['diagnostico']['causa']['destruicao_tecidos'],
                                'doenca_cronica'                   => $request['diagnostico']['causa']['doenca_cronica'],
                                'expo_ambiental'                   => $request['diagnostico']['causa']['expo_ambiental'],
                                'imunidade_adquirida'              => $request['diagnostico']['causa']['imunidade_adquirida'],
                                'imunossupressao'                  => $request['diagnostico']['causa']['imunossupressao'],
                                'procedimentos_invasivos'          => $request['diagnostico']['causa']['procedimentos_invasivos'],
                                'tecidos_inviaveis'                => $request['diagnostico']['causa']['tecidos_inviaveis'],
                                'infeccao_trauma'                  => $request['diagnostico']['causa']['infeccao_trauma'],
                                'risco_infec_outro'                => $request['diagnostico']['causa']['risco_infec_outro'],
                                'aumento_temp'                     => $request['diagnostico']['causa']['aumento_temp'],
                                'dimunuicao_temp'                  => $request['diagnostico']['causa']['dimunuicao_temp'],
                                'aumento_taxa'                     => $request['diagnostico']['causa']['aumento_taxa'],
                                'diminuicao_taxa'                  => $request['diagnostico']['causa']['diminuicao_taxa'],
                                'temperatura_desnutricao'          => $request['diagnostico']['causa']['temperatura_desnutricao'],
                                'desidratacao'                     => $request['diagnostico']['causa']['desidratacao'],
                                'dimin_capacidade_transpirar'      => $request['diagnostico']['causa']['dimin_capacidade_transpirar'],
                                'doenca'                           => $request['diagnostico']['causa']['doenca'],
                                'ambiente_quente'                  => $request['diagnostico']['causa']['ambiente_quente'],
                                'ambiente_frio'                    => $request['diagnostico']['causa']['ambiente_frio'],
                                'medicamentos'                     => $request['diagnostico']['causa']['medicamentos'],
                                'temperatura_trauma'               => $request['diagnostico']['causa']['temperatura_trauma'],
                                'vestimentas_inadequadas'          => $request['diagnostico']['causa']['vestimentas_inadequadas'],
                                'dano_hipotalamo'                  => $request['diagnostico']['causa']['dano_hipotalamo'],
                                'inatividade'                      => $request['diagnostico']['causa']['inatividade'],
                                'envelhecimento'                   => $request['diagnostico']['causa']['envelhecimento'],
                                'capac_tremer'                     => $request['diagnostico']['causa']['capac_tremer'],
                                'alt_temp_outro'                   => $request['diagnostico']['causa']['alt_temp_outro'],
                                'lesao_tecidual'                   => $request['diagnostico']['causa']['lesao_tecidual'],
                                'diagnostico_cirurgia'             => $request['diagnostico']['causa']['diagnostico_cirurgia'],
                                'infeccoes'                        => $request['diagnostico']['causa']['infeccoes'],
                                'diagnostico_vazio_outro'          => $request['diagnostico']['causa']['diagnostico_vazio_outro'],
                                'dor_aguda_obs'                    => $request['diagnostico']['causa']['dor_aguda_obs'],
                                'cancer'                           => $request['diagnostico']['causa']['cancer'],
                                'doencas_arteriais'                => $request['diagnostico']['causa']['doencas_arteriais'],
                                'infeccao'                         => $request['diagnostico']['causa']['infeccao'],
                                'dor_cronica_outro'                => $request['diagnostico']['causa']['dor_cronica_outro'],
                                'equipamento_externo'              => $request['diagnostico']['causa']['equipamento_externo'],
                                'forca_insuficiente'               => $request['diagnostico']['causa']['forca_insuficiente'],
                                'fadiga'                           => $request['diagnostico']['causa']['fadiga'],
                                'cirurgias'                        => $request['diagnostico']['causa']['cirurgias'],
                                'inconsciencia'                    => $request['diagnostico']['causa']['inconsciencia'],
                                'andar_aclive'                     => $request['diagnostico']['causa']['andar_aclive'],
                                'andar_declive'                    => $request['diagnostico']['causa']['andar_declive'],
                                'andar_superficies_irregulares'    => $request['diagnostico']['causa']['andar_superficies_irregulares'],
                                'percorrer_distancia_necessarias'  => $request['diagnostico']['causa']['percorrer_distancia_necessarias'],
                                'subir_escadas'                    => $request['diagnostico']['causa']['subir_escadas'],
                                'forca_muscular_insuficiente'      => $request['diagnostico']['causa']['forca_muscular_insuficiente'],
                                'humor_deprimido'                  => $request['diagnostico']['causa']['humor_deprimido'],
                                'prejuizo_musculo_esqueletico'     => $request['diagnostico']['causa']['prejuizo_musculo_esqueletico'],
                                'prejuizo_neuromuscular'           => $request['diagnostico']['causa']['prejuizo_neuromuscular'],
                                'medo_cair'                        => $request['diagnostico']['causa']['medo_cair'],
                                'obesidade'                        => $request['diagnostico']['causa']['obesidade'],
                                'visao_prejudicada'                => $request['diagnostico']['causa']['visao_prejudicada'],
                                'mobilidade_fisica_outro'          => $request['diagnostico']['causa']['mobilidade_fisica_outro'],
                                'alto_nivel_estresse'              => $request['diagnostico']['causa']['alto_nivel_estresse'],
                                'ansiedade'                        => $request['diagnostico']['causa']['ansiedade'],
                                'radiacao'                         => $request['diagnostico']['causa']['radiacao'],
                                'abuso_laxantes'                   => $request['diagnostico']['causa']['abuso_laxantes'],
                                'alimentacao_sonda'                => $request['diagnostico']['causa']['alimentacao_sonda'],
                                'contaminacao'                     => $request['diagnostico']['causa']['contaminacao'],
                                'efeitos_medicacoes'               => $request['diagnostico']['causa']['efeitos_medicacoes'],
                                'inflamacao'                       => $request['diagnostico']['causa']['inflamacao'],
                                'irritacao'                        => $request['diagnostico']['causa']['irritacao'],
                                'mal_absorcao'                     => $request['diagnostico']['causa']['mal_absorcao'],
                                'parasitas'                        => $request['diagnostico']['causa']['parasitas'],
                                'processos_infecciosos'            => $request['diagnostico']['causa']['processos_infecciosos'],
                                'eliminicacoes_fisiologicas_outro' => $request['diagnostico']['causa']['eliminicacoes_fisiologicas_outro'],
                                'aumento_peso'                     => $request['diagnostico']['causa']['aumento_peso'],
                                'perda_peso'                       => $request['diagnostico']['causa']['perda_peso'],
                                'saude_fisica_instavel'            => $request['diagnostico']['causa']['saude_fisica_instavel'],
                                'saude_mental_instavel'            => $request['diagnostico']['causa']['saude_mental_instavel'],
                                'estresse'                         => $request['diagnostico']['causa']['estresse'],
                                'falta_aceitacao_diagnostico'      => $request['diagnostico']['causa']['falta_aceitacao_diagnostico'],
                                'falta_adesao_diabete'             => $request['diagnostico']['causa']['falta_adesao_diabete'],
                                'falta_controle_diabete'           => $request['diagnostico']['causa']['falta_controle_diabete'],
                                'ingestao_alimentar_inadequada'    => $request['diagnostico']['causa']['ingestao_alimentar_inadequada'],
                                'monitoracao_inadequada_glicemia'  => $request['diagnostico']['causa']['monitoracao_inadequada_glicemia'],
                                'nivel_fisica_inadequada'          => $request['diagnostico']['causa']['nivel_fisica_inadequada'],
                                'risco_glicemia_outro'             => $request['diagnostico']['causa']['risco_glicemia_outro'],
                            ])->id,

                            'protocolosintomas_id' => ProtocoloSinaisSintomaFeridas::create([
                                'incisao_cirurgica'                 => $request['diagnostico']['sintomas']['incisao_cirurgica'],
                                'hematoma'                          => $request['diagnostico']['sintomas']['hematoma'],
                                'hiperemia'                         => $request['diagnostico']['sintomas']['hiperemia'],
                                'edema'                             => $request['diagnostico']['sintomas']['edema'],
                                'calor'                             => $request['diagnostico']['sintomas']['calor'],
                                'turgor'                            => $request['diagnostico']['sintomas']['turgor'],
                                'perda_solucao_continuidade'        => $request['diagnostico']['sintomas']['perda_solucao_continuidade'],
                                'estase_fluidos_organico'           => $request['diagnostico']['sintomas']['estase_fluidos_organico'],
                                'mudanca_ph_secrecoes'              => $request['diagnostico']['sintomas']['mudanca_ph_secrecoes'],
                                'integridade_risco_sintomas_outro'  => $request['diagnostico']['sintomas']['integridade_risco_sintomas_outro'],
                                'exsudado_purulento'                => $request['diagnostico']['sintomas']['exsudado_purulento'],
                                'exsudado_odor_fetido'              => $request['diagnostico']['sintomas']['exsudado_odor_fetido'],
                                'risco_infeccao_taquicardia'        => $request['diagnostico']['sintomas']['risco_infeccao_taquicardia'],
                                'hiperemia_maior'                   => $request['diagnostico']['sintomas']['hiperemia_maior'],
                                'celulite'                          => $request['diagnostico']['sintomas']['celulite'],
                                'calor_local'                       => $request['diagnostico']['sintomas']['calor_local'],
                                'alt_temp_corporal'                 => $request['diagnostico']['sintomas']['alt_temp_corporal'],
                                'dor'                               => $request['diagnostico']['sintomas']['dor'],
                                'tecidos_inviaveis'                 => $request['diagnostico']['sintomas']['tecidos_inviaveis'],
                                'risco_infeccao_sintomas_outro'     => $request['diagnostico']['sintomas']['risco_infeccao_sintomas_outro'],
                                'hipertemia'                        => $request['diagnostico']['sintomas']['hipertemia'],
                                'hipotermia'                        => $request['diagnostico']['sintomas']['hipotermia'],
                                'convulsoes'                        => $request['diagnostico']['sintomas']['convulsoes'],
                                'pele_avermelhada'                  => $request['diagnostico']['sintomas']['pele_avermelhada'],
                                'taquicardia'                       => $request['diagnostico']['sintomas']['taquicardia'],
                                'taquipneia'                        => $request['diagnostico']['sintomas']['taquipneia'],
                                'cianose_leitos_ungueais'           => $request['diagnostico']['sintomas']['cianose_leitos_ungueais'],
                                'hipertensao'                       => $request['diagnostico']['sintomas']['hipertensao'],
                                'hipotensao'                        => $request['diagnostico']['sintomas']['hipotensao'],
                                'hipoglicemia'                      => $request['diagnostico']['sintomas']['hipoglicemia'],
                                'palidez'                           => $request['diagnostico']['sintomas']['palidez'],
                                'pele_fria'                         => $request['diagnostico']['sintomas']['pele_fria'],
                                'piloerecao'                        => $request['diagnostico']['sintomas']['piloerecao'],
                                'capilar_lento'                     => $request['diagnostico']['sintomas']['capilar_lento'],
                                'tremor'                            => $request['diagnostico']['sintomas']['tremor'],
                                'alt_temp_corpo_sintomas_outro'     => $request['diagnostico']['sintomas']['alt_temp_corpo_sintomas_outro'],
                                'relato_verbal'                     => $request['diagnostico']['sintomas']['relato_verbal'],
                                'expre_facial_dor'                  => $request['diagnostico']['sintomas']['expre_facial_dor'],
                                'incap_realizar_acoes'              => $request['diagnostico']['sintomas']['incap_realizar_acoes'],
                                'diagnostico_vazio_sintomas_outro'  => $request['diagnostico']['sintomas']['diagnostico_vazio_sintomas_outro'],
                                'dor_cronica_relato_verbal'         => $request['diagnostico']['sintomas']['dor_cronica_relato_verbal'],
                                'dor_cronica_expre_facial_dor'      => $request['diagnostico']['sintomas']['dor_cronica_expre_facial_dor'],
                                'dor_cronica_incap_realizar_acoes'  => $request['diagnostico']['sintomas']['dor_cronica_incap_realizar_acoes'],
                                'dor_cronica_sintomas_outro'        => $request['diagnostico']['sintomas']['dor_cronica_sintomas_outro'],
                                'restric_imposta_movi'              => $request['diagnostico']['sintomas']['restric_imposta_movi'],
                                'capac_motora_prejudicada'          => $request['diagnostico']['sintomas']['capac_motora_prejudicada'],
                                'inconsciencia'                     => $request['diagnostico']['sintomas']['inconsciencia'],
                                'mobilidade_dor'                    => $request['diagnostico']['sintomas']['mobilidade_dor'],
                                'equilibrio_prejudicado'            => $request['diagnostico']['sintomas']['equilibrio_prejudicado'],
                                'mobilidade_fisica_sintomas_outro'  => $request['diagnostico']['sintomas']['mobilidade_fisica_sintomas_outro'],
                                'tres_evacuacoes_fezes'             => $request['diagnostico']['sintomas']['tres_evacuacoes_fezes'],
                                'urgencia_evacuar'                  => $request['diagnostico']['sintomas']['urgencia_evacuar'],
                                'alt_eliminacoes_sintomas_outro'    => $request['diagnostico']['sintomas']['alt_eliminacoes_sintomas_outro'],
                                'perda_peso'                        => $request['diagnostico']['sintomas']['perda_peso'],
                                'aumento_peso'                      => $request['diagnostico']['sintomas']['aumento_peso'],
                                'sede'                              => $request['diagnostico']['sintomas']['sede'],
                                'risco_glicemia_sintomas_outro'     => $request['diagnostico']['sintomas']['risco_glicemia_sintomas_outro'],
                            ])->id
                        ])->id,

                        
                    ])->id,
            ]);
            
            if ($request['anexos']) {
                foreach ($request['anexos'] as $anexo) {
                    $md5 = md5_file($anexo['file']);
                    $caminho = 'anexos/';
                    $nome = $md5 . '.' . explode(';', explode('/', $anexo['file'])[1])[0];
                    $file = explode(',', $anexo['file'])[1];
                    Storage::put($caminho . $nome, base64_decode($file));
                    Anexo::create([
                        'anexo_id'   => $protocoloAvaliacaoFerida->id,
                        'anexo_type' => 'app\Models\ProtocoloAvaliacaoFeridas',
                        'caminho'    => $caminho . $nome,
                        'nome'       => $anexo['nome'],
                        'descricao'  => ""
                    ]);
                }
            }
        });
        return response()->json([
            'toast' => [
                'text'  => 'Protocolo cadastrado com sucesso!',
                'color' => 'success',
                'duration' => 2000
            ]
        ], 200)
        ->header('Content-Type', 'application/json');
          
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ProtocoloAvaliacaoFerida  $protocoloAvaliacaoFerida
     * @return \Illuminate\Http\Response
     */
    public function show(ProtocoloAvaliacaoFerida $protocoloAvaliacaoFerida)
    {
        $protocoloAvaliacaoFerida->protocolo;
        $protocoloAvaliacaoFerida->protocolo->cliente;
        $protocoloAvaliacaoFerida->protocolo->paciente;
        $protocoloAvaliacaoFerida->protocolopesdiabeticos;
        $protocoloAvaliacaoFerida->protocololesao;
        // $protocoloAvaliacaoFerida->protocololaserterapia;
        $protocoloAvaliacaoFerida->protocololaserterapia->protocolodiagnosticos;
        $protocoloAvaliacaoFerida->protocololaserterapia->protocolodiagnosticos->protocolocausa;
        $protocoloAvaliacaoFerida->protocololaserterapia->protocolodiagnosticos->protocolosintomas;
        
        return $protocoloAvaliacaoFerida;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ProtocoloAvaliacaoFerida  $protocoloAvaliacaoFerida
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ProtocoloAvaliacaoFerida $protocoloAvaliacaoFerida)
    {
        DB::transaction(function () use($request){
            $protocoloferida = ProtocoloAvaliacaoFerida::updateOrCreate(
            [
                'id'  => $request['id'],
            ],
            [
            'protocolo_id' => ProtocoloSkin::updateOrCreate(
                [
                    'id'   => $request['id']
                ],
                [
                    'empresa_id'             => $request['empresa_id'],
                    'paciente_id'            => $request['protocolo']['paciente_id'],
                    'cliente_id'             => $request['protocolo']['cliente_id'],
                    'medico'                 => $request['protocolo']['medico'],
                    'diagnostico'            => $request['protocolo']['diagnostico'],
                    'afastado'               => $request['protocolo']['afastado'],
                    'aposentado'             => $request['protocolo']['aposentado'],
                    'nivel_consciencia'      => $request['protocolo']['nivel_consciencia'],
                    'obs_nivel_consciencia'  => $request['protocolo']['obs_nivel_consciencia'],
                    'hipertensao_arterial'   => $request['protocolo']['hipertensao_arterial'],
                    'pa'                     => $request['protocolo']['pa'],
                    'data'                   => $request['protocolo']['data'],
                    'diabetes'               => $request['protocolo']['diabetes'],
                    'glicemia'               => $request['protocolo']['glicemia'],
                    'hematocrito'            => $request['protocolo']['hematocrito'],
                    'hemoglobina'            => $request['protocolo']['hemoglobina'],
                    'proteinas_totais'       => $request['protocolo']['proteinas_totais'],
                    'pcr'                    => $request['protocolo']['pcr'],
                    'albumina'               => $request['protocolo']['albumina'],
                    'outros'                 => $request['protocolo']['outros'],
                    'peso'                   => $request['protocolo']['peso'],
                    'altura'                 => $request['protocolo']['altura'],
                    'acamado'                => $request['protocolo']['acamado'],
                    'deambula'               => $request['protocolo']['deambula'],
                    'cadeira_rodas'          => $request['protocolo']['cadeira_rodas'],
                    'muleta'                 => $request['protocolo']['muleta'],
                    'andador'                => $request['protocolo']['andador'],
                    'c_ajuda'                => $request['protocolo']['c_ajuda'],
                    'destreza_manual'        => $request['protocolo']['destreza_manual'],
                    'auto_cuidado'           => $request['protocolo']['auto_cuidado'],
                    'cafe_manha'             => $request['protocolo']['cafe_manha'],
                    'almoco'                 => $request['protocolo']['almoco'],
                    'cafe_tarde'             => $request['protocolo']['cafe_tarde'],
                    'jantar'                 => $request['protocolo']['jantar'],
                    'ceia'                   => $request['protocolo']['ceia'],
                    'rica'                   => $request['protocolo']['rica'],
                    'urinaria'               => $request['protocolo']['urinaria'],
                    'fecal'                  => $request['protocolo']['fecal'],
                    'medicamento'            => $request['protocolo']['medicamento'],
                    'av_central'             => $request['protocolo']['av_central'],
                    'av_periferico'          => $request['protocolo']['av_periferico'],
                    'av_jelco'               => $request['protocolo']['av_jelco'],
                    'av_scalp'               => $request['protocolo']['av_scalp'],
                    'av_intracath'           => $request['protocolo']['av_intracath'],
                    'av_portocath'           => $request['protocolo']['av_portocath'],
                    'av_piv'                 => $request['protocolo']['av_piv'],
                    'av_data'                => $request['protocolo']['av_data'],
                    'tbg_fuma'               => $request['protocolo']['tbg_fuma'],
                    'tbg_tempo'              => $request['protocolo']['tbg_tempo'],
                    'tbg_cigarros_dia'       => $request['protocolo']['tbg_cigarros_dia'],
                    'tbg_atual'              => $request['protocolo']['tbg_atual'],
                    'tbg_tempo_parou'        => $request['protocolo']['tbg_tempo_parou'],
                    'alergia'                => $request['protocolo']['alergia'],
                    'alergia_qual'           => $request['protocolo']['alergia_qual'],
                    'oxigenioterapia'        => $request['protocolo']['oxigenioterapia'],
                    'ox_cateter_nasal'       => $request['protocolo']['ox_cateter_nasal'],
                    'ox_mascara_nebulizacao' => $request['protocolo']['ox_mascara_nebulizacao'],
                    'ox_cateter_venturi'     => $request['protocolo']['ox_cateter_venturi'],
                    'ox_bipap'               => $request['protocolo']['ox_bipap'],
                    'ox_cpap'                => $request['protocolo']['ox_cpap'],
                    'al_vo'                  => $request['protocolo']['al_vo'],
                    'al_sng'                 => $request['protocolo']['al_sng'],
                    'al_sne'                 => $request['protocolo']['al_sne'],
                    'al_gastrostomia'        => $request['protocolo']['al_gastrostomia'],
                    'al_jejunostomia'        => $request['protocolo']['al_jejunostomia'],
                    'al_parenteral'          => $request['protocolo']['al_parenteral'],
                    'as_sozinho'             => $request['protocolo']['as_sozinho'],
                    'as_familiares'          => $request['protocolo']['as_familiares'],
                    'as_cuidador'            => $request['protocolo']['as_cuidador'],
                    'as_casa_terrea'         => $request['protocolo']['as_casa_terrea'],
                    'as_apartamento'         => $request['protocolo']['as_apartamento'],
                    'as_casa_escadas'        => $request['protocolo']['as_casa_escadas'],
                    'as_outros'              => $request['protocolo']['as_outros'],
                    'cp_normal'              => $request['protocolo']['cp_normal'],
                    'cp_seca'                => $request['protocolo']['cp_seca'],
                    'cp_oleosa'              => $request['protocolo']['cp_oleosa'],
                    'cp_mista'               => $request['protocolo']['cp_mista'],
                    'cp_ressecada'           => $request['protocolo']['cp_ressecada'],
                    'cp_outra'               => $request['protocolo']['cp_outra'],
                    'ds_visao'               => $request['protocolo']['ds_visao'],
                    'ds_audicao'             => $request['protocolo']['ds_audicao'],
                    'cpa_pele_oleosa'        => $request['protocolo']['cpa_pele_oleosa'],
                    'cpa_cicatriz'           => $request['protocolo']['cpa_cicatriz'],
                    'cpa_dobras_gordura'     => $request['protocolo']['cpa_dobras_gordura'],
                    'cpa_dermatologica'      => $request['protocolo']['cpa_dermatologica'],
                    'cpa_atual'              => $request['protocolo']['cpa_atual'],
                    'cpa_qual'               => $request['protocolo']['cpa_qual'],
                    'crd_lesoes'             => $request['protocolo']['crd_lesoes'],
                    'crd_fistulas'           => $request['protocolo']['crd_fistulas'],
                    'crd_fisuras'            => $request['protocolo']['crd_fisuras'],
                    'crd_incontinencia'      => $request['protocolo']['crd_incontinencia'],
                    'crd_outros'             => $request['protocolo']['crd_outros'],
                ])->id,
                'ferida_cirurgica'          => $request['ferida_cirurgica'],
                'ferida_lesao_pressao'      => $request['ferida_lesao_pressao'],
                'ferida_diabetica'          => $request['ferida_diabetica'],
                'ferida_venosa'             => $request['ferida_venosa'],
                'ferida_arterial'           => $request['ferida_arterial'],
                'ferida_outros'             => $request['ferida_outros'],
                'tempo_lesao'               => $request['tempo_lesao'],
                'feridas_anteriores'        => $request['feridas_anteriores'],
                'popliteo_d'                => $request['popliteo_d'],
                'popliteo_e'                => $request['popliteo_e'],
                'pedial_d'                  => $request['pedial_d'],
                'pedial_e'                  => $request['pedial_e'],
                'perfusao_menor'            => $request['perfusao_menor'],
                'perfusao_maior'            => $request['perfusao_maior'],
                'mensuracao_anterior'       => $request['mensuracao_anterior'],
                'mensuracao_atual'          => $request['mensuracao_atual'],
                'lp_1'                      => $request['lp_1'],
                'lp_2'                      => $request['lp_2'],
                'lp_3'                      => $request['lp_3'],
                'lp_4'                      => $request['lp_4'],
                'lp_dispositivo_medico'     => $request['lp_dispositivo_medico'],
                'lp_ltp'                    => $request['lp_ltp'],
                'lp_impossivel_estadiar'    => $request['lp_impossivel_estadiar'],
                'skin_1'                    => $request['skin_1'],
                'skin_2'                    => $request['skin_2'],
                'skin_3'                    => $request['skin_3'],
                'venosa_superficial'        => $request['venosa_superficial'],
                'venosa_parcial'            => $request['venosa_parcial'],
                'venosa_total'              => $request['venosa_total'],
                'leitof_granulacao'         => $request['leitof_granulacao'],
                'leitof_esfacelo'           => $request['leitof_esfacelo'],
                'leitof_necrose'            => $request['leitof_necrose'],
                'leitof_biofilme'           => $request['leitof_biofilme'],
                'leitof_outros'             => $request['leitof_outros'],
                'leitof_gangrena'           => $request['leitof_gangrena'],
                'desbridamento_autolitico'  => $request['desbridamento_autolitico'],
                'desbridamento_enzimatico'  => $request['desbridamento_enzimatico'],
                'desbridamento_mecanico'    => $request['desbridamento_mecanico'],
                'desbridamento_cirurgico'   => $request['desbridamento_cirurgico'],
                'margem_epitelizada'        => $request['margem_epitelizada'],
                'margem_epitelizando'       => $request['margem_epitelizando'],
                'margem_necrosada'          => $request['margem_necrosada'],
                'margem_hiperemiada'        => $request['margem_hiperemiada'],
                'margem_epibole'            => $request['margem_epibole'],
                'margem_aderida'            => $request['margem_aderida'],
                'margem_descolada_total'    => $request['margem_descolada_total'],
                'margem_descolada_parcial'  => $request['margem_descolada_parcial'],
                'descolada_parcial_hrs'     => $request['descolada_parcial_hrs'],
                'descolada_parcial_cm'      => $request['descolada_parcial_cm'],
                'margem_outros'             => $request['margem_outros'],
                'pele_hiperemiada'          => $request['pele_hiperemiada'],
                'pele_ressecada'            => $request['pele_ressecada'],
                'pele_queratose'            => $request['pele_queratose'],
                'pele_eczema'               => $request['pele_eczema'],
                'pele_lesoes'               => $request['pele_lesoes'],
                'pele_dermatite'            => $request['pele_dermatite'],
                'pele_outro'                => $request['pele_outro'],
                'exsudato_seroso'           => $request['exsudato_seroso'],
                'exsudato_translucido'      => $request['exsudato_translucido'],
                'exsudato_sanguinolento'    => $request['exsudato_sanguinolento'],
                'exsudato_serosanguinolento'  => $request['exsudato_serosanguinolento'],
                'exsudato_purulento'  => $request['exsudato_purulento'],
                'exsudato_piosanguinolento'  => $request['exsudato_piosanguinolento'],
                'exsudato_esverdeado'  => $request['exsudato_esverdeado'],
                'exsudato_outro'  => $request['exsudato_outro'],
                'volume_escasso'  => $request['volume_escasso'],
                'volume_pequeno'  => $request['volume_pequeno'],
                'volume_moderado'  => $request['volume_moderado'],
                'volume_grande'  => $request['volume_grande'],
                'volume_abundante'  => $request['volume_abundante'],
                'coleta_cultura'  => $request['coleta_cultura'],
                'coleta_cultura_resultado'  => $request['coleta_cultura_resultado'],

                'protocololesao_id' => ProtocoloAvaliacaoLesaoPressao::updateOrCreate(
                    [
                        'id'   => $request['lesao_pressao']['id']
                    ],
                    [
                        'braden_total_limitado'            => $request['lesao_pressao']['braden_total_limitado'],
                        'braden_muito_limitado'            => $request['lesao_pressao']['braden_muito_limitado'],
                        'braden_levemente_limitado'        => $request['lesao_pressao']['braden_levemente_limitado'],
                        'braden_nenhuma_limitacao'         => $request['lesao_pressao']['braden_nenhuma_limitacao'],
                        'braden_completamente_molhada'     => $request['lesao_pressao']['braden_completamente_molhada'],
                        'braden_muito_molhada'             => $request['lesao_pressao']['braden_muito_molhada'],
                        'braden_ocasionalmente_molhada'    => $request['lesao_pressao']['braden_ocasionalmente_molhada'],
                        'braden_raramente_molhada'         => $request['lesao_pressao']['braden_raramente_molhada'],
                        'braden_acamado'                   => $request['lesao_pressao']['braden_acamado'],
                        'braden_confinado_cadeira'         => $request['lesao_pressao']['braden_confinado_cadeira'],
                        'braden_anda_ocasionalmente'       => $request['lesao_pressao']['braden_anda_ocasionalmente'],
                        'braden_anda_frequentemente'       => $request['lesao_pressao']['braden_anda_frequentemente'],
                        'braden_totalmente_imovel'         => $request['lesao_pressao']['braden_totalmente_imovel'],
                        'braden_bastante_limitado'         => $request['lesao_pressao']['braden_bastante_limitado'],
                        'braden_levemente_limitado2'       => $request['lesao_pressao']['braden_levemente_limitado2'],
                        'braden_nenhuma_limitacao2'        => $request['lesao_pressao']['braden_nenhuma_limitacao2'],
                        'braden_muito_pobre'               => $request['lesao_pressao']['braden_muito_pobre'],
                        'braden_provavelmente_inadequado'  => $request['lesao_pressao']['braden_provavelmente_inadequado'],
                        'braden_adequado'                  => $request['lesao_pressao']['braden_adequado'],
                        'braden_excelente'                 => $request['lesao_pressao']['braden_excelente'],
                        'braden_problema'                  => $request['lesao_pressao']['braden_problema'],
                        'braden_problema_potencial'        => $request['lesao_pressao']['braden_problema_potencial'],
                        'braden_nenhum_problema'           => $request['lesao_pressao']['braden_nenhum_problema'],
                        'colchao_inadequado'               => $request['lesao_pressao']['colchao_inadequado'],
                        'colchao_agua'                     => $request['lesao_pressao']['colchao_agua'],
                        'colchao_ar'                       => $request['lesao_pressao']['colchao_ar'],
                        'colchao_piramidal'                => $request['lesao_pressao']['colchao_piramidal'],
                        'protetor'                         => $request['lesao_pressao']['protetor'],
                        'protetor_espuma'                  => $request['lesao_pressao']['protetor_espuma'],
                        'protetor_agua'                    => $request['lesao_pressao']['protetor_agua'],
                        'protetor_ar'                      => $request['lesao_pressao']['protetor_ar'],
                        'protetor_gel'                     => $request['lesao_pressao']['protetor_gel'],
                        'posicionadores'                   => $request['lesao_pressao']['posicionadores'],
                        'posicionadores_regiao'            => $request['lesao_pressao']['posicionadores_regiao'],
                        'banho_leito'                      => $request['lesao_pressao']['banho_leito'],
                        'banho_aspersao'                   => $request['lesao_pressao']['banho_aspersao'],
                        'banho_frequencia'                 => $request['lesao_pressao']['banho_frequencia'],
                        'higiene_intima'                   => $request['lesao_pressao']['higiene_intima'],
                        'sabonetes'                        => $request['lesao_pressao']['sabonetes'],
                        'hidratantes'                      => $request['lesao_pressao']['hidratantes'],
                        'hidratantes_qual'                 => $request['lesao_pressao']['hidratantes_qual'],
                        'cuidador_nome'                    => $request['lesao_pressao']['cuidador_nome'],
                        'cuidador_idade'                   => "",
                        'cuidador_data_nasc'               => $request['lesao_pressao']['cuidador_data_nasc'],
                        'cuidador_disponibilidade'         => $request['lesao_pressao']['cuidador_disponibilidade'],
                        'cuidador_observacoes'             => $request['lesao_pressao']['cuidador_observacoes'],
                ])->id,

                'protocolopesdiabeticos_id' => ProtocoloAvaliacaoPesDiabetico::updateOrCreate(
                    [
                        'id'   => $request['pe_diabetico']['id']
                    ],
                    [
                        'pe_esquerdo_calos1'      => $request['pe_diabetico']['pe_esquerdo_calos1'],
                        'pe_esquerdo_calos2'      => $request['pe_diabetico']['pe_esquerdo_calos2'],
                        'pe_esquerdo_calos3'      => $request['pe_diabetico']['pe_esquerdo_calos3'],
                        'pe_esquerdo_calos4'      => $request['pe_diabetico']['pe_esquerdo_calos4'],
                        'pe_esquerdo_ulcera1'     => $request['pe_diabetico']['pe_esquerdo_ulcera1'],
                        'pe_esquerdo_ulcera2'     => $request['pe_diabetico']['pe_esquerdo_ulcera2'],
                        'pe_esquerdo_ulcera3'     => $request['pe_diabetico']['pe_esquerdo_ulcera3'],
                        'pe_esquerdo_ulcera4'     => $request['pe_diabetico']['pe_esquerdo_ulcera4'],
                        'pe_esquerdo_preulcera1'  => $request['pe_diabetico']['pe_esquerdo_preulcera1'],
                        'pe_esquerdo_preulcera2'  => $request['pe_diabetico']['pe_esquerdo_preulcera2'],
                        'pe_esquerdo_preulcera3'  => $request['pe_diabetico']['pe_esquerdo_preulcera3'],
                        'pe_esquerdo_preulcera4'  => $request['pe_diabetico']['pe_esquerdo_preulcera4'],
                        'pe_direito_calos1'       => $request['pe_diabetico']['pe_direito_calos1'],
                        'pe_direito_calos2'       => $request['pe_diabetico']['pe_direito_calos2'],
                        'pe_direito_calos3'       => $request['pe_diabetico']['pe_direito_calos3'],
                        'pe_direito_calos4'       => $request['pe_diabetico']['pe_direito_calos4'],
                        'pe_direito_ulcera1'      => $request['pe_diabetico']['pe_direito_ulcera1'],
                        'pe_direito_ulcera2'      => $request['pe_diabetico']['pe_direito_ulcera2'],
                        'pe_direito_ulcera3'      => $request['pe_diabetico']['pe_direito_ulcera3'],
                        'pe_direito_ulcera4'      => $request['pe_diabetico']['pe_direito_ulcera4'],
                        'pe_direito_preulcera1'   => $request['pe_diabetico']['pe_direito_preulcera1'],
                        'pe_direito_preulcera2'   => $request['pe_diabetico']['pe_direito_preulcera2'],
                        'pe_direito_preulcera3'   => $request['pe_diabetico']['pe_direito_preulcera3'],
                        'pe_direito_preulcera4'   => $request['pe_diabetico']['pe_direito_preulcera4'],
                        'monofilamento'           => $request['pe_diabetico']['monofilamento'],
                ])->id,

                'protocololaserterapia_id' => ProtocoloAvaliacaoLaserTerapia::updateOrCreate(
                    [
                        'id' => $request['laserterapia']['id']
                    ],
                    [
                        'laserterapia_localizacao'          => $request['laserterapia']['laserterapia_localizacao'],
                        'tratamento_ferida_cirurgica'       => $request['laserterapia']['tratamento_ferida_cirurgica'],
                        'tratamento_ferida_lesao_pressao'   => $request['laserterapia']['tratamento_ferida_lesao_pressao'],
                        'tratamento_ferida_neuropatica'     => $request['laserterapia']['tratamento_ferida_neuropatica'],
                        'tratamento_ferida_venosa'          => $request['laserterapia']['tratamento_ferida_venosa'],
                        'tratamento_ferida_arterial'        => $request['laserterapia']['tratamento_ferida_arterial'],
                        'tratamento_ferida_outros'          => $request['laserterapia']['tratamento_ferida_outros'],
                        'estadiamento'                      => $request['laserterapia']['estadiamento'],
                        'mensuracao'                        => $request['laserterapia']['mensuracao'],
                        'leito_ferida'                      => $request['laserterapia']['leito_ferida'],
                        'margem_ferida'                     => $request['laserterapia']['margem_ferida'],
                        'pele_redor'                        => $request['laserterapia']['pele_redor'],
                        'exsudato'                          => $request['laserterapia']['exsudato'],
                        'classificacao_dor'                 => $request['laserterapia']['classificacao_dor'],
                        'area_lesao_larg'                   => $request['laserterapia']['area_lesao_larg'],
                        'area_lesao_comp'                   => $request['laserterapia']['area_lesao_comp'],
                        'energia_total_j'                   => $request['laserterapia']['energia_total_j'],
                        'energia_total_area'                => $request['laserterapia']['energia_total_area'],
                        'pontos_area_afetada'               => $request['laserterapia']['pontos_area_afetada'],
                        'area_afetada_pontos'               => $request['laserterapia']['area_afetada_pontos'],
                        'area_afetada_v'                    => $request['laserterapia']['area_afetada_v'],
                        'area_afetada_if'                   => $request['laserterapia']['area_afetada_if'],
                        'area_afetada_pontual'              => $request['laserterapia']['area_afetada_pontual'],
                        'area_afetada_varredura'            => $request['laserterapia']['area_afetada_varredura'],
                        'pontos_redor_area'                 => $request['laserterapia']['pontos_redor_area'],
                        'redor_area_pontos'                 => $request['laserterapia']['redor_area_pontos'],
                        'redor_area_v'                      => $request['laserterapia']['redor_area_v'],
                        'redor_area_if'                     => $request['laserterapia']['redor_area_if'],
                        'escala_dor_obs'                    => $request['laserterapia']['escala_dor_obs'],

                    'pro_diagnostico_id' => ProtocoloDiagnosticoFerida::updateOrCreate(
                        [
                            'id' => $request['diagnostico']['id']
                        ],
                        [
                            'integridade_tissular'  => $request['diagnostico']['integridade_tissular'],
                            'risco_infeccao'        => $request['diagnostico']['risco_infeccao'],
                            'alt_temperatura'       => $request['diagnostico']['alt_temperatura'],
                            'diagnostico_vazio'     => $request['diagnostico']['diagnostico_vazio'],
                            'dor_aguda'             => $request['diagnostico']['dor_aguda'],
                            'dor_cronica'           => $request['diagnostico']['dor_cronica'],
                            'mobilidade_fisica'     => $request['diagnostico']['mobilidade_fisica'],
                            'alt_eliminacoes'       => $request['diagnostico']['alt_eliminacoes'],
                            'risco_glicemia'        => $request['diagnostico']['risco_glicemia'],

                        'protocolocausa_id' => ProtocoloCausaFerida::updateOrCreate(
                            [
                                'id' => $request['diagnostico']['causa']['id']
                            ],
                            [
                                'circulacao_prejudicada'           => $request['diagnostico']['causa']['circulacao_prejudicada'],
                                'conhecimento_insuf'               => $request['diagnostico']['causa']['conhecimento_insuf'],
                                'integridade_inflamacao'           => $request['diagnostico']['causa']['integridade_inflamacao'],
                                'lesao_tecido_subcutaneo'          => $request['diagnostico']['causa']['lesao_tecido_subcutaneo'],
                                'lesao_tecido_epidermico'          => $request['diagnostico']['causa']['lesao_tecido_epidermico'],
                                'tumores'                          => $request['diagnostico']['causa']['tumores'],
                                'fratura'                          => $request['diagnostico']['causa']['fratura'],
                                'integridade_trauma'               => $request['diagnostico']['causa']['integridade_trauma'],
                                'edema'                            => $request['diagnostico']['causa']['edema'],
                                'exp_umidade_excessiva'            => $request['diagnostico']['causa']['exp_umidade_excessiva'],
                                'mudancas_turgor_pele'             => $request['diagnostico']['causa']['mudancas_turgor_pele'],
                                'proeminencias_osseas'             => $request['diagnostico']['causa']['proeminencias_osseas'],
                                'ulceras_pressao'                  => $request['diagnostico']['causa']['ulceras_pressao'],
                                'fragilidade_pele'                 => $request['diagnostico']['causa']['fragilidade_pele'],
                                'imobilidade'                      => $request['diagnostico']['causa']['imobilidade'],
                                'ferida_cirurgica'                 => $request['diagnostico']['causa']['ferida_cirurgica'],
                                'ulceras_etiologias'               => $request['diagnostico']['causa']['ulceras_etiologias'],
                                'doencas_pele'                     => $request['diagnostico']['causa']['doencas_pele'],
                                'integridade_outro'                => $request['diagnostico']['causa']['integridade_outro'],
                                'agente_farmaceutico'              => $request['diagnostico']['causa']['agente_farmaceutico'],
                                'conhecimento_insu_expo_patogenos' => $request['diagnostico']['causa']['conhecimento_insu_expo_patogenos'],
                                'defesas_primarias'                => $request['diagnostico']['causa']['defesas_primarias'],
                                'defesas_secundarias'              => $request['diagnostico']['causa']['defesas_secundarias'],
                                'infeccao_desnutricao'             => $request['diagnostico']['causa']['infeccao_desnutricao'],
                                'destruicao_tecidos'               => $request['diagnostico']['causa']['destruicao_tecidos'],
                                'doenca_cronica'                   => $request['diagnostico']['causa']['doenca_cronica'],
                                'expo_ambiental'                   => $request['diagnostico']['causa']['expo_ambiental'],
                                'imunidade_adquirida'              => $request['diagnostico']['causa']['imunidade_adquirida'],
                                'imunossupressao'                  => $request['diagnostico']['causa']['imunossupressao'],
                                'procedimentos_invasivos'          => $request['diagnostico']['causa']['procedimentos_invasivos'],
                                'tecidos_inviaveis'                => $request['diagnostico']['causa']['tecidos_inviaveis'],
                                'infeccao_trauma'                  => $request['diagnostico']['causa']['infeccao_trauma'],
                                'risco_infec_outro'                => $request['diagnostico']['causa']['risco_infec_outro'],
                                'aumento_temp'                     => $request['diagnostico']['causa']['aumento_temp'],
                                'dimunuicao_temp'                  => $request['diagnostico']['causa']['dimunuicao_temp'],
                                'aumento_taxa'                     => $request['diagnostico']['causa']['aumento_taxa'],
                                'diminuicao_taxa'                  => $request['diagnostico']['causa']['diminuicao_taxa'],
                                'temperatura_desnutricao'          => $request['diagnostico']['causa']['temperatura_desnutricao'],
                                'desidratacao'                     => $request['diagnostico']['causa']['desidratacao'],
                                'dimin_capacidade_transpirar'      => $request['diagnostico']['causa']['dimin_capacidade_transpirar'],
                                'doenca'                           => $request['diagnostico']['causa']['doenca'],
                                'ambiente_quente'                  => $request['diagnostico']['causa']['ambiente_quente'],
                                'ambiente_frio'                    => $request['diagnostico']['causa']['ambiente_frio'],
                                'medicamentos'                     => $request['diagnostico']['causa']['medicamentos'],
                                'temperatura_trauma'               => $request['diagnostico']['causa']['temperatura_trauma'],
                                'vestimentas_inadequadas'          => $request['diagnostico']['causa']['vestimentas_inadequadas'],
                                'dano_hipotalamo'                  => $request['diagnostico']['causa']['dano_hipotalamo'],
                                'inatividade'                      => $request['diagnostico']['causa']['inatividade'],
                                'envelhecimento'                   => $request['diagnostico']['causa']['envelhecimento'],
                                'capac_tremer'                     => $request['diagnostico']['causa']['capac_tremer'],
                                'alt_temp_outro'                   => $request['diagnostico']['causa']['alt_temp_outro'],
                                'lesao_tecidual'                   => $request['diagnostico']['causa']['lesao_tecidual'],
                                'diagnostico_cirurgia'             => $request['diagnostico']['causa']['diagnostico_cirurgia'],
                                'infeccoes'                        => $request['diagnostico']['causa']['infeccoes'],
                                'diagnostico_vazio_outro'          => $request['diagnostico']['causa']['diagnostico_vazio_outro'],
                                'dor_aguda_obs'                    => $request['diagnostico']['causa']['dor_aguda_obs'],
                                'cancer'                           => $request['diagnostico']['causa']['cancer'],
                                'doencas_arteriais'                => $request['diagnostico']['causa']['doencas_arteriais'],
                                'infeccao'                         => $request['diagnostico']['causa']['infeccao'],
                                'dor_cronica_outro'                => $request['diagnostico']['causa']['dor_cronica_outro'],
                                'equipamento_externo'              => $request['diagnostico']['causa']['equipamento_externo'],
                                'forca_insuficiente'               => $request['diagnostico']['causa']['forca_insuficiente'],
                                'fadiga'                           => $request['diagnostico']['causa']['fadiga'],
                                'cirurgias'                        => $request['diagnostico']['causa']['cirurgias'],
                                'inconsciencia'                    => $request['diagnostico']['causa']['inconsciencia'],
                                'andar_aclive'                     => $request['diagnostico']['causa']['andar_aclive'],
                                'andar_declive'                    => $request['diagnostico']['causa']['andar_declive'],
                                'andar_superficies_irregulares'    => $request['diagnostico']['causa']['andar_superficies_irregulares'],
                                'percorrer_distancia_necessarias'  => $request['diagnostico']['causa']['percorrer_distancia_necessarias'],
                                'subir_escadas'                    => $request['diagnostico']['causa']['subir_escadas'],
                                'forca_muscular_insuficiente'      => $request['diagnostico']['causa']['forca_muscular_insuficiente'],
                                'humor_deprimido'                  => $request['diagnostico']['causa']['humor_deprimido'],
                                'prejuizo_musculo_esqueletico'     => $request['diagnostico']['causa']['prejuizo_musculo_esqueletico'],
                                'prejuizo_neuromuscular'           => $request['diagnostico']['causa']['prejuizo_neuromuscular'],
                                'medo_cair'                        => $request['diagnostico']['causa']['medo_cair'],
                                'obesidade'                        => $request['diagnostico']['causa']['obesidade'],
                                'visao_prejudicada'                => $request['diagnostico']['causa']['visao_prejudicada'],
                                'mobilidade_fisica_outro'          => $request['diagnostico']['causa']['mobilidade_fisica_outro'],
                                'alto_nivel_estresse'              => $request['diagnostico']['causa']['alto_nivel_estresse'],
                                'ansiedade'                        => $request['diagnostico']['causa']['ansiedade'],
                                'radiacao'                         => $request['diagnostico']['causa']['radiacao'],
                                'abuso_laxantes'                   => $request['diagnostico']['causa']['abuso_laxantes'],
                                'alimentacao_sonda'                => $request['diagnostico']['causa']['alimentacao_sonda'],
                                'contaminacao'                     => $request['diagnostico']['causa']['contaminacao'],
                                'efeitos_medicacoes'               => $request['diagnostico']['causa']['efeitos_medicacoes'],
                                'inflamacao'                       => $request['diagnostico']['causa']['inflamacao'],
                                'irritacao'                        => $request['diagnostico']['causa']['irritacao'],
                                'mal_absorcao'                     => $request['diagnostico']['causa']['mal_absorcao'],
                                'parasitas'                        => $request['diagnostico']['causa']['parasitas'],
                                'processos_infecciosos'            => $request['diagnostico']['causa']['processos_infecciosos'],
                                'eliminicacoes_fisiologicas_outro' => $request['diagnostico']['causa']['eliminicacoes_fisiologicas_outro'],
                                'aumento_peso'                     => $request['diagnostico']['causa']['aumento_peso'],
                                'perda_peso'                       => $request['diagnostico']['causa']['perda_peso'],
                                'saude_fisica_instavel'            => $request['diagnostico']['causa']['saude_fisica_instavel'],
                                'saude_mental_instavel'            => $request['diagnostico']['causa']['saude_mental_instavel'],
                                'estresse'                         => $request['diagnostico']['causa']['estresse'],
                                'falta_aceitacao_diagnostico'      => $request['diagnostico']['causa']['falta_aceitacao_diagnostico'],
                                'falta_adesao_diabete'             => $request['diagnostico']['causa']['falta_adesao_diabete'],
                                'falta_controle_diabete'           => $request['diagnostico']['causa']['falta_controle_diabete'],
                                'ingestao_alimentar_inadequada'    => $request['diagnostico']['causa']['ingestao_alimentar_inadequada'],
                                'monitoracao_inadequada_glicemia'  => $request['diagnostico']['causa']['monitoracao_inadequada_glicemia'],
                                'nivel_fisica_inadequada'          => $request['diagnostico']['causa']['nivel_fisica_inadequada'],
                                'risco_glicemia_outro'             => $request['diagnostico']['causa']['risco_glicemia_outro'],
                        ])->id,

                        'protocolosintomas_id' => ProtocoloSinaisSintomaFeridas::updateOrCreate(
                            [
                                'id' => $request['diagnostico']['sintomas']['id']
                            ],
                            [
                                'incisao_cirurgica'                 => $request['diagnostico']['sintomas']['incisao_cirurgica'],
                                'hematoma'                          => $request['diagnostico']['sintomas']['hematoma'],
                                'hiperemia'                         => $request['diagnostico']['sintomas']['hiperemia'],
                                'edema'                             => $request['diagnostico']['sintomas']['edema'],
                                'calor'                             => $request['diagnostico']['sintomas']['calor'],
                                'turgor'                            => $request['diagnostico']['sintomas']['turgor'],
                                'perda_solucao_continuidade'        => $request['diagnostico']['sintomas']['perda_solucao_continuidade'],
                                'estase_fluidos_organico'           => $request['diagnostico']['sintomas']['estase_fluidos_organico'],
                                'mudanca_ph_secrecoes'              => $request['diagnostico']['sintomas']['mudanca_ph_secrecoes'],
                                'integridade_risco_sintomas_outro'  => $request['diagnostico']['sintomas']['integridade_risco_sintomas_outro'],
                                'exsudado_purulento'                => $request['diagnostico']['sintomas']['exsudado_purulento'],
                                'exsudado_odor_fetido'              => $request['diagnostico']['sintomas']['exsudado_odor_fetido'],
                                'risco_infeccao_taquicardia'        => $request['diagnostico']['sintomas']['risco_infeccao_taquicardia'],
                                'hiperemia_maior'                   => $request['diagnostico']['sintomas']['hiperemia_maior'],
                                'celulite'                          => $request['diagnostico']['sintomas']['celulite'],
                                'calor_local'                       => $request['diagnostico']['sintomas']['calor_local'],
                                'alt_temp_corporal'                 => $request['diagnostico']['sintomas']['alt_temp_corporal'],
                                'dor'                               => $request['diagnostico']['sintomas']['dor'],
                                'tecidos_inviaveis'                 => $request['diagnostico']['sintomas']['tecidos_inviaveis'],
                                'risco_infeccao_sintomas_outro'     => $request['diagnostico']['sintomas']['risco_infeccao_sintomas_outro'],
                                'hipertemia'                        => $request['diagnostico']['sintomas']['hipertemia'],
                                'hipotermia'                        => $request['diagnostico']['sintomas']['hipotermia'],
                                'convulsoes'                        => $request['diagnostico']['sintomas']['convulsoes'],
                                'pele_avermelhada'                  => $request['diagnostico']['sintomas']['pele_avermelhada'],
                                'taquicardia'                       => $request['diagnostico']['sintomas']['taquicardia'],
                                'taquipneia'                        => $request['diagnostico']['sintomas']['taquipneia'],
                                'cianose_leitos_ungueais'           => $request['diagnostico']['sintomas']['cianose_leitos_ungueais'],
                                'hipertensao'                       => $request['diagnostico']['sintomas']['hipertensao'],
                                'hipotensao'                        => $request['diagnostico']['sintomas']['hipotensao'],
                                'hipoglicemia'                      => $request['diagnostico']['sintomas']['hipoglicemia'],
                                'palidez'                           => $request['diagnostico']['sintomas']['palidez'],
                                'pele_fria'                         => $request['diagnostico']['sintomas']['pele_fria'],
                                'piloerecao'                        => $request['diagnostico']['sintomas']['piloerecao'],
                                'capilar_lento'                     => $request['diagnostico']['sintomas']['capilar_lento'],
                                'tremor'                            => $request['diagnostico']['sintomas']['tremor'],
                                'alt_temp_corpo_sintomas_outro'     => $request['diagnostico']['sintomas']['alt_temp_corpo_sintomas_outro'],
                                'relato_verbal'                     => $request['diagnostico']['sintomas']['relato_verbal'],
                                'expre_facial_dor'                  => $request['diagnostico']['sintomas']['expre_facial_dor'],
                                'incap_realizar_acoes'              => $request['diagnostico']['sintomas']['incap_realizar_acoes'],
                                'diagnostico_vazio_sintomas_outro'  => $request['diagnostico']['sintomas']['diagnostico_vazio_sintomas_outro'],
                                'dor_cronica_relato_verbal'         => $request['diagnostico']['sintomas']['dor_cronica_relato_verbal'],
                                'dor_cronica_expre_facial_dor'      => $request['diagnostico']['sintomas']['dor_cronica_expre_facial_dor'],
                                'dor_cronica_incap_realizar_acoes'  => $request['diagnostico']['sintomas']['dor_cronica_incap_realizar_acoes'],
                                'dor_cronica_sintomas_outro'        => $request['diagnostico']['sintomas']['dor_cronica_sintomas_outro'],
                                'restric_imposta_movi'              => $request['diagnostico']['sintomas']['restric_imposta_movi'],
                                'capac_motora_prejudicada'          => $request['diagnostico']['sintomas']['capac_motora_prejudicada'],
                                'inconsciencia'                     => $request['diagnostico']['sintomas']['inconsciencia'],
                                'mobilidade_dor'                    => $request['diagnostico']['sintomas']['mobilidade_dor'],
                                'equilibrio_prejudicado'            => $request['diagnostico']['sintomas']['equilibrio_prejudicado'],
                                'mobilidade_fisica_sintomas_outro'  => $request['diagnostico']['sintomas']['mobilidade_fisica_sintomas_outro'],
                                'tres_evacuacoes_fezes'             => $request['diagnostico']['sintomas']['tres_evacuacoes_fezes'],
                                'urgencia_evacuar'                  => $request['diagnostico']['sintomas']['urgencia_evacuar'],
                                'alt_eliminacoes_sintomas_outro'    => $request['diagnostico']['sintomas']['alt_eliminacoes_sintomas_outro'],
                                'perda_peso'                        => $request['diagnostico']['sintomas']['perda_peso'],
                                'aumento_peso'                      => $request['diagnostico']['sintomas']['aumento_peso'],
                                'sede'                              => $request['diagnostico']['sintomas']['sede'],
                                'risco_glicemia_sintomas_outro'     => $request['diagnostico']['sintomas']['risco_glicemia_sintomas_outro'],
                        ])->id
                    ])->id,

                    
                ])->id,
            ]);
        });
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ProtocoloAvaliacaoFerida  $protocoloAvaliacaoFerida
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProtocoloAvaliacaoFerida $protocoloAvaliacaoFerida)
    {
        $protocoloAvaliacaoFerida->delete();
    }
}
